[versions]
caffeine = "3.2.3"
commons-codec = "1.21.0"
commons-compress = "1.28.0"
commons-io = "2.21.0"
commons-lang = "3.20.0"
json = "20250517"
junit-jupiter = "5.14.3"
netty = "4.2.10.Final"
oci-registry = "0.7.0"
reactor-kotlin = "1.3.0"
reactor-netty = "1.3.3"

[libraries]
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
commons-lang = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang" }
json = { module = "org.json:json", version.ref = "json" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
netty-bom = { module = "io.netty:netty-bom", version.ref = "netty" }
netty-resolver-dns-native-macos = { module = "io.netty:netty-resolver-dns-native-macos", version.ref = "netty" }
oci-registry = { module = "io.github.sgtsilvio:oci-registry", version.ref = "oci-registry" }
reactor-kotlin = { module = "io.projectreactor.kotlin:reactor-kotlin-extensions", version.ref = "reactor-kotlin" }
reactor-netty = { module = "io.projectreactor.netty:reactor-netty", version.ref = "reactor-netty" }

[plugins]
pluginPublish = { id = "com.gradle.plugin-publish", version = "2.0.0" }
defaults = { id = "io.github.sgtsilvio.gradle.defaults", version = "0.2.0" }
metadata = { id = "io.github.sgtsilvio.gradle.metadata", version = "0.6.0" }
